Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "sonarqube-server"

  config.vm.network "private_network", ip: "192.168.56.21"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "sonarqube-server"
    vb.memory = 6144
    vb.cpus = 4
  end

  config.vm.provision "shell", 
    path: "bootstrap.sh",
    privileged: true
end