Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "teamcity-server"

  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "teamcity-server"
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.provision "shell",
    path: "bootstrap.sh",
    privileged: true
end